### ISSUE TITLE
Can't run web-computeration-fixed

### ISSUE THREAD

**Issue by FrancescoMusmanno** [justcatthefish/justctf-2020#1]
Hi, I tried to install web-computeration fixed in docker on my machine, it builds correctly, but it doesn't run properly. When I visit http://localhost it correctly redirects me to https://localhost on port 443 according to the caddy settings, but throws an error of secure connection failed with the error code: SSL_ERROR_INTERNAL_ERROR_ALERT. I think the problem is about the loading of the ssl certificate in the machine, but I don't know how to fix... Any ideas? Thanks in advance for the response

**Comment by disconnect3d** [comment]
Hi, sorry for the late response. No idea how to set it up properly at this point. It could be that SSL is not required for this task, but if it is, u would have to setup it properly so that u need a domain and get a SSL cert for it -- I think the compose does this automagically but yeah, I don't know on top of my head how it was set up.
